=== redpanda-ai/Meerkat/meerkat/web_service/schema_input_datadeal.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "meerkat_categorize input schema",
	"definitions": {
		"transaction_record": {
			"type": "object",
			"properties": {
				"transaction_id" : { "type": "number" },
				"description" : { "type": "string" },
				"city": { "type": "string" },
				"state": { "type": "string" },
				"country": { "type": "string" },
				"postal_code": { "type": "string" },
				"RNN_merchant_name": { "type": "string" },
				"website_url": { "type": "string" },
				"store_number": {
					"type": "array",
					"items": { "type": "string" }
				},
				"phone_number": { "type": "string" },
				"amount" : { "type": "number" },
				"ledger_entry" : { "enum" : [ "debit", "credit" ] },
				"date" : { "type": "string" }
			},
			"additionalProperties" : false,
			"required": ["transaction_id", "description", "amount", "date", "ledger_entry"]
		}
	},
	"description": "A schema for defining input into 'meerkat_categorize'",
	"type" : "object",
	"properties" : {
		"cobrand_id" : {
			"description" : "Yodlee's number to uniquely identify the cobrand",
			"type" : "number"
		},
		"user_id" : {
			"description" : "Yodlee's number to uniquely identify a user within a cobrand",
			"type" : "number"
		},
		"container" : { "enum" : [ "bank", "card" ] },
		"debug" : { "enum" : [ true, false ] },
		"transaction_list" : {
			"description" : "An array containing at least one transaction_record.",
			"type" : "array",
			"items" : {
				"allOf": [
					{"$ref": "#/definitions/transaction_record"}
				]
			},
			"minItems": 1,
			"maxItems": 1000,
			"uniqueItems": true
		},
		"user_city" : {
			"description" : "User's city",
			"type" : "string"
		},
		"user_state" : {
			"description" : "User's state",
			"type" : "string"
		},
		"user_country" : {
			"description" : "User's country",
			"type" : "string",
			"maxLength" : 2,
			"minLength" : 2
		},
		"cobrand_region" : {
			"description" : "Cobrand's region",
			"type" : "integer"
		},
		"services_list" : {
			"description" : "Services to be enabled",
			"type" : "array",
			"items" : {
				"type" : "string"
			},
			"minItems" : 1
		}
	},
	"required": ["cobrand_id", "user_id", "container", "transaction_list"],
	"additionalProperties" : false
}

=== redpanda-ai/Meerkat/meerkat/web_service/example_input_datadeal.json
{
	"cobrand_id" : 1234,
	"user_id" : 2345,
	"container" : "card",
	"debug" : false,
	"transaction_list" : [
        {
            "RNN_merchant_name": "MCDONALD'S",
            "amount": 10,
            "city": "ERIE",
            "country": "US",
            "date": "2016-10-14",
            "description": "MCDONALD'S M4361 OF PA   ERIE         PA",
            "ledger_entry": "debit",
            "phone_number": "",
            "postal_code": "16510",
            "state": "PA",
            "store_number": ["M4361"],
            "transaction_id": 45431
        },
        {
            "RNN_merchant_name": "U-HAUL",
            "amount": 10,
            "city": "PHILADELPHIA",
            "country": "US",
            "date": "2016-10-14",
            "description": "U-HAUL CT CHELTEHAM      PHILADELPHIA PA",
            "ledger_entry": "debit",
            "phone_number": "",
            "postal_code": "19138",
            "state": "PA",
            "store_number": [],
            "transaction_id": 76554
        },
        {
            "RNN_merchant_name": "DOLRTREE",
            "amount": 10,
            "city": "LEOMINSTER",
            "country": "US",
            "date": "2016-10-14",
            "description": "DOLRTREE 4474 00044743   LEOMINSTER   MA",
            "ledger_entry": "debit",
            "phone_number": "",
            "postal_code": "1453",
            "state": "MA",
            "store_number": ["4474 00044743"],
            "transaction_id": 71755
        }
	]
}

=== redpanda-ai/Meerkat/web_service_tester/one_ledger.json
{"debug": false, "services_list":["bloom_filter", "cnn_merchant", "cnn_subtype", "search"], "container":"bank", "transaction_list":[ { "date":"2014-08-10T00:00:00", "description":"taco bell scarsdale, ny", "amount":59.0, "transaction_id":5024853, "ledger_entry":"debit" } ], "cobrand_id":99, "user_id":12177727 }
